dist: xenial
language: generic

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

# install - install any dependencies required
install:
  - curl -s -H "Authorization:bearer $GITHUB_TOKEN" https://api.github.com/repos/gohugoio/hugo/releases/latest | grep -o -P '(?<=browser_download_url". ").*?Linux-64bit.deb' | head -1  | xargs wget
  - sudo dpkg -i hugo*.deb

before_script:
  - rm -rf public 2> /dev/null

# script - run the build script
script:
  - bash ./preprocess.sh
  - set -xv && hugo && cd public && git init && git add -A && git commit -m 'deploy' && git push -f "https://${GITHUB_TOKEN}@github.com/si9ma/YunBlog.git" master:gh-pages && cd -