baseurl = "https://www.si9ma.com"
title = "si9ma's blog"
author = "si9ma"
canonifyurls = true
paginate = 5
theme = "aether"
disqusShortname = "si9ma"

[params]
brand = "si9ma"
description = "si9ma's personal blog"
homeimg= "/img/home.jpg"
bgimg= "/img/bg.jpg"